# serverless.yml

service: sqs-triggers-demo-old-fashioned

provider:
  name: aws
  runtime: nodejs6.10
  profile: sls
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
        - "sqs:GetQueueUrl"
      Resource: "arn:aws:sqs:${self:provider.region}:811338114639:MyQueue2"
    - Effect: "Allow"
      Action:
        - "sqs:ListQueues"
      Resource: "arn:aws:sqs:${self:provider.region}:811338114639:*"


functions:
  sender:
    handler: sender.handler
    events:
      - http:
          path: v1/sender
          method: post
  receiver:
    handler: receiver.handler
    events:
      - schedule: rate(1 minute)

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue2"


# export QUEUE_URL=`aws sqs get-queue-url --queue-name MyQueue2 --query 'QueueUrl' --output text --profile=sls`
# aws sqs send-message --queue-url ${QUEUE_URL} --message-body "test" --profile=sls
